### ISSUE TITLE
jscc.testing.checks.get_empty_files: Empty JSON files are silently ignored

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/jscc#6]
I'm not sure if it's the intended behaviour, but files with a `.json` suffix that contain only whitespace are silently ignored by this check.

**Comment by jpmckinney** [comment]
We had witnessed files that were 0 bytes. I haven't witnessed (or been aware of) files that are only whitespace. We can certainly include those in this check.

**Comment by jpmckinney** [comment]
Ah, I see the problem - JSON files that are whitespace only cause a JSON decode error, which is interpreted as being a non-empty (but invalid) file. I can strip the text before parsing to fix this bug.

**Comment by jpmckinney** [comment]
Fixed in 0.1.1 6ff1c542e8648567053f62fafff27b86d89fbfca

**Comment by duncandewhurst** [comment]
Thanks for the speedy turnaround!
