### ISSUE TITLE
JSON Schema Draft 2020-12 RefResolutionError

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/jscc#8]
When following the examples on https://jscc.readthedocs.io/en/latest/api/testing/checks.html (with the fix suggested in https://github.com/open-contracting/jscc/issues/7) and `metaschema` set to `https://json-schema.org/draft/2020-12/schema`, pytest throws the following error:

> FAILED tests/test_schema.py::test_schema_valid[/mnt/9E863086863060C7/GDrive/Work/Repositories/risk_data_library/jscc-test/schema.json-schema.json-data0] - jsonschema.exceptions.RefResolutionError: unknown url type: 'meta/core'

The full traceback is long so I put it in a [Gist](https://gist.github.com/duncandewhurst/b889911599a983286a8aa9630bc710ce).

Here's the full code I tested with:

```python
import jsonref
import pytest
from jscc.testing.filesystem import walk_json_data
from jscc.schema import is_json_schema
from jscc.testing.checks import (validate_array_items, validate_codelist_enum, validate_deep_properties,
                         validate_items_type, validate_letter_case, validate_merge_properties,
                         validate_metadata_presence, validate_null_type, validate_object_id, validate_ref,
                         validate_schema)
from jscc.testing.util import http_get

schemas = [(path, name, data) for path, name, _, data in walk_json_data() if is_json_schema(data)]
metaschema = http_get('https://json-schema.org/draft/2020-12/schema').json()

@pytest.mark.parametrize('path,name,data', schemas)
def test_schema_valid(path, name, data):
    validate_json_schema(path, name, data, metaschema)

def validate_json_schema(path, name, data, schema):
    errors = 0

    errors += validate_schema(path, data, schema)
    errors += validate_array_items(path, data)
    errors += validate_items_type(path, data)
    errors += validate_codelist_enum(path, data)
    errors += validate_letter_case(path, data)
    errors += validate_merge_properties(path, data)
    errors += validate_ref(path, data)
    errors += validate_metadata_presence(path, data)
    errors += validate_object_id(path, jsonref.replace_refs(data))
    errors += validate_null_type(path, data)
    # Here, we don't add to `errors`, in order to not count these warnings as errors.
    validate_deep_properties(path, data)

    assert not errors, 'One or more JSON Schema files are invalid. See warnings below.'
```

The error seems to be related to the first item in the `allOf` at the top-level of https://json-schema.org/draft/2020-12/schema:

```json
{"$ref": "meta/core"}
```

**Comment by jpmckinney** [comment]
Do you have JSON files to test with? The code does nothing for me as it finds no schemas.

**Comment by jpmckinney** [comment]
Ah, yeah, jscc uses the Draft4Validator:

> from jsonschema.validators import Draft4Validator as validator

**Comment by duncandewhurst** [comment]
Ah, I see! Thanks for the speedy response.

I created a [fork](https://github.com/OpenDataServices/jscc-2020-12) that simply replaces `Draft4Validator` with `Draft202012Validator` in `checks.py`. It seems to work as expected and the tests in this repo pass.

It looks simple enough to import both validators, add an argument to `validate_schema` to choose which to use, and default to `Draft4Validator` if the argument isn't specified. I can prepare a PR if you like?

**Comment by jpmckinney** [comment]
You can now use any validator in 0.2.1.

See [changelog](https://jscc.readthedocs.io/en/latest/changelog.html) (or updated docs) for what changes to make.

**Comment by duncandewhurst** [comment]
Brilliant, thank you!
