### ISSUE TITLE
What does get_invalid_csv_files actually test?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/jscc#9]
From my testing, `csv.DictReader` seems to accept any type of file and an error is only thrown when you try to iterate through the reader. For example, I renamed an arbitrary binary file to `file.csv` and `get_invalid_csv_files` returned no errors.

**Comment by jpmckinney** [comment]
It's indeed difficult to create invalid CSVs. It might very well be impossible.

Not even this is considered invalid:

```csv
a,b
"ab"c,foo
```

**Comment by jpmckinney** [comment]
I've removed it in 0.2.2.

**Comment by duncandewhurst** [comment]
Thanks!
